model: gemini-2.0-pro-exp
api: google
max_tokens: null
temperature: null
concurrent_requests: 5
config:
  max_output_tokens: 16000
  temperature: 0
read_cost: 1.2
write_cost: 5
human_readable_id: gemini-2.0-pro
date: "2025-02-05"
other_params:
  open: false
  creator: Google