model: gemini-2.5-flash
api: google
max_tokens: null
temperature: null
top_p: null
concurrent_requests: 8
max_tokens: 10000
read_cost: 0.15
write_cost: 3.5
human_readable_id: Gemini 2.5 Flash (Thinking)
date: "2025-04-18"
other_params:
  open: false
  creator: Google