model: gemini-2.5-pro-preview-05-06
api: google
max_tokens: null
temperature: null
top_p: null
concurrent_requests: 8
max_tokens: 130000
read_cost: 0
write_cost: 0
human_readable_id: Gemini 2.5 Pro (05-06)
date: "2025-05-06"
other_params:
  open: false
  creator: Google