model: gemini-2.5-pro
api: google
max_tokens: null
temperature: null
top_p: null
concurrent_requests: 1
max_tokens: 130000
read_cost: 1.25
write_cost: 10.00
human_readable_id: Gemini 2.5 Pro (agent)
date: "2025-03-25"
other_params:
  open: false
  creator: Google