model: gemini-2.0-flash-exp
api: google
max_tokens: null
temperature: null
top_p: null
config:
  max_output_tokens: 16000
  temperature: 0
concurrent_requests: 5
read_cost: 0.1
write_cost: 0.4
human_readable_id: gemini-2.0-flash
date: "2025-02-05"
other_params:
  open: false
  creator: Google