model: gemini-2.0-flash-thinking-exp
api: google
max_tokens: null
temperature: null
concurrent_requests: 5
config:
  max_output_tokens: null
  temperature: null
read_cost: 0
write_cost: 0
human_readable_id: gemini-2.0-flash-thinking
date: "2025-02-05"
other_params:
  open: false
  creator: Google