model: grok-3-mini
api: xai
max_tokens: 131000
read_cost: 0.3
write_cost: 0.5
human_readable_id: Grok 3 Mini (low)
concurrent_requests: 8
reasoning_effort: low
temperature: 0.2
date: "2025-04-09"
other_params:
  open: false
  creator: xAI