model: grok-3-mini-beta
api: xai
max_tokens: 131000
read_cost: 0.3
write_cost: 0.5
human_readable_id: Grok 3 Mini (high)
concurrent_requests: 10
reasoning_effort: high
temperature: 0.2
date: "2025-04-09"
other_params:
  open: false
  creator: xAI