model: grok-4-1-fast-reasoning
api: xai
max_tokens: 130000
read_cost: 0.2
write_cost: 0.5
human_readable_id: Grok 4.1 Fast (Reasoning)
concurrent_requests: 16
temperature: null
top_p: null
date: "2025-11-20"
other_params:
  open: false
  creator: xAI