model: gpt-5--high
api: openai
max_tokens: 128000
read_cost: 1.25
write_cost: 10
concurrent_requests: 32
temperature: null
top_p: null
human_readable_id: GPT-5 (high)
batch_processing: false
use_openai_responses_api: true
date: "2025-08-07"
reasoning:
  summary: "auto"
other_params:
  open: false
  creator: OpenAI