model: gpt-5.2--xhigh
api: openai
max_tokens: 128000
read_cost: 1.75
write_cost: 14
concurrent_requests: 32
temperature: null
top_p: null
human_readable_id: GPT-5.2 (high)
batch_processing: false
background: true
use_openai_responses_api: true
date: "2025-12-11"
reasoning:
  summary: "auto"
other_params:
  open: false
  creator: OpenAI