model: o3-mini--medium
api: openai
max_tokens: 32000
read_cost: 1.1
write_cost: 4.4
human_readable_id: o3-mini (medium)
batch_processing: true
use_openai_responses_api: true
date: "2025-01-31"
other_params:
  open: false
  creator: OpenAI