model: o3--high
api: openai
max_tokens: 100000
read_cost: 2
write_cost: 8
human_readable_id: o3 (high)
batch_processing: false
use_openai_responses_api: true
date: "2025-04-16"
concurrent_requests: 4
other_params:
  open: false
  creator: OpenAI