model: o4-mini--low
api: openai
max_tokens: 100000
read_cost: 1.1
write_cost: 4.4
human_readable_id: o4-mini (low)
batch_processing: false
use_openai_responses_api: true
date: "2025-04-16"
other_params:
  open: false
  creator: OpenAI