model: "openai/gpt-oss-20b"
api: together
max_tokens: 128000
read_cost: 0.05
write_cost: 0.2
concurrent_requests: 16
reasoning_effort: high
human_readable_id: GPT OSS 20B (high)
date: "2025-08-05"
other_params:
  open: true
  creator: OpenAI
  parameters: 21
  active_parameters: 3.6