model: claude-opus-4-0
api: anthropic
max_tokens: 32000
concurrent_requests: 4
temperature: null
top_p: null
thinking:
  type: enabled 
  budget_tokens: 31000
read_cost: 5
write_cost: 25
batch_processing: false
human_readable_id: Claude-Opus-4.1 (Think)
date: "2025-08-05"
other_params:
  open: false
  creator: Anthropic