model: claude-opus-4-0
api: anthropic
max_tokens: 32000
concurrent_requests: 4
temperature: 1
top_p: null
thinking:
  type: enabled 
  budget_tokens: 31000
read_cost: 15
write_cost: 75
batch_processing: true
human_readable_id: Claude-Opus-4.0 (Think)
date: "2025-05-22"
other_params:
  open: false
  creator: Anthropic