instruction: "Put your final answer within \\boxed{{}}.\nThe answer is an integer between 0 and 999 inclusive."
strict_parsing: false
n_problems: 30
date: "2025-02-12"
dataset_path: MathArena/aime_2025
