model: glm-4.5v
api: glm
max_tokens: 16000
concurrent_requests: 1
temperature: 0.6
top_p: 0.95
read_cost: 0.6
write_cost: 1.8
human_readable_id: GLM 4.5V
date: "2025-08-01"
other_params:
  open: true
  creator: Z.ai
  parameters: 106
  active_parameters: 12