model: glm-4.5-air
api: glm
max_tokens: 81920
concurrent_requests: 60
temperature: 0.6
top_p: 0.95
read_cost: 0.2
write_cost: 1.1
human_readable_id: GLM 4.5 Air
date: "2025-08-01"
other_params:
  open: true
  creator: Z.ai
  parameters: 106
  active_parameters: 12