model: glm-4.6
api: glm
max_tokens: 122880
concurrent_requests: 5
temperature: 1
top_p: null
read_cost: 0.6
write_cost: 2.2
human_readable_id: GLM 4.6
date: "2025-09-30"
other_params:
  open: true
  creator: Z.ai
  parameters: 355
  active_parameters: 32