model: moonshotai/kimi-k2.5
api: openrouter
max_tokens: 256000
temperature: 1.0 
concurrent_requests: 32
read_cost: 0.60
write_cost: 3
context_limit: 256000
human_readable_id: Kimi K2.5 (Think)
date: "2026-01-27"
reasoning_effort: high
extra_body:
  provider:
    allow_fallbacks: False
    order:
    - moonshotai
other_params:
  open: true
  creator: Moonshot AI
  parameters: 1000
  active_parameters: 32