model: qwen/qwen3-30b-a3b
api: openrouter
max_tokens: 32000
temperature: 0.6
top_p: 0.95
concurrent_requests: 10
extra_body:
  provider:
    allow_fallbacks: False
    order:
    - nebius
read_cost: 0.1
write_cost: 0.3
human_readable_id: Qwen3-30B-A3B
date: "2025-04-29"
other_params:
  open: true
  creator: Qwen
  parameters: 30
  active_parameters: 3