model: qwen/qwen3-235b-a22b-thinking-2507
api: openrouter
max_tokens: 81920
temperature: 0.6
top_p: 0.95
top_k: 20
extra_body:
  provider:
    allow_fallbacks: False
    order:
    - deepinfra
concurrent_requests: 1
read_cost: 0.6
write_cost: 1.2
human_readable_id: Qwen3-235B-2507-Think
date: "2025-07-25"
other_params:
  open: true
  creator: Qwen
  parameters: 235
  active_parameters: 22