model: Qwen/QwQ-32B
api: together
max_tokens: 32000
temperature: 0.6
top_p: 0.95
top_k: 40
read_cost: 1.2
write_cost: 1.2
human_readable_id: QwQ-32B
date: "2025-03-05"
concurrent_requests: 1
other_params:
  open: true
  creator: Qwen
  parameters: 32
  active_parameters: 32