model: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
api: together
max_tokens: 32000
temperature: 0.6
top_p: 0.95 
read_cost: 0.2
write_cost: 0.6
human_readable_id: DeepSeek-R1-Distill-70B
date: "2025-01-21"
other_params:
  open: true
  creator: DeepSeek
  parameters: 70
  active_parameters: 70