model: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
api: together
max_tokens: 32000
temperature: 0.6
top_p: 0.95
read_cost: 0.18
write_cost: 0.18
human_readable_id: DeepSeek-R1-Distill-1.5B
date: "2025-01-21"
other_params:
  open: true
  creator: DeepSeek
  parameters: 1.5
  active_parameters: 1.5
