model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
api: vllm
max_tokens: 32000
temperature: 0.6
top_p: 0.95
concurrent_requests: 200
read_cost: 0.3
write_cost: 0.3
human_readable_id: DeepSeek-R1-Distill-32B
date: "2025-01-21"
other_params:
  open: true
  creator: DeepSeek
  parameters: 32
  active_parameters: 32