model: "deepseek-ai/DeepSeek-OCR"
api: custom
base_url: http://localhost:8000/v1
max_tokens: 8100
temperature: 0
read_cost: 0
write_cost: 0
concurrent_requests: 16
human_readable_id: DeepSeek-OCR
date: "2025-08-05"